version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "2"
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --timeout 300 -b 0.0.0.0:5000 "flight_tracker:create_app()"
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flight_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
